services:
    fivem:
        container_name: fivem
        build: runtimes/alpine-3
        image: shiva/fivem:latest
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        stdin_open: true
        tty: true
        init: true
        platform: linux/amd64
        environment:
            - LICENSE_KEY="${LICENSE_KEY}"
            - STEAM_KEY="${STEAM_KEY}"
            - RCON_PASSWORD="${RCON_PASSWORD:-changeme}"
            - APP_DEBUG="${APP_DEBUG:-false}"
            - NO_DEFAULT_CONFIG="${NO_DEFAULT_CONFIG}"
            - NO_LICENSE_KEY="${NO_LICENSE_KEY}"
            - NO_STEAM_KEY="${NO_STEAM_KEY}"
            - NO_ONESYNC="${NO_ONESYNC}"
        volumes:
            - ./fivem:/config:rw
            - ./txData:/txData:rw
        ports:
            - "${FORWARD_FIVEM_PORT:-30120}:30120/tcp"
            - "${FORWARD_FIVEM_PORT:-30120}:30120/udp"
            - '${FORWARD_TXADMIN_PORT:-40120}:40120/tcp'
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - shiva
    mysql:
        container_name: mysql
        image: mysql:8.0
        command:
            --default-authentication-plugin=mysql_native_password
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        stdin_open: true
        tty: true
        init: true
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-password}"
            # uncomment below if you want to automatically create and select a database
            MYSQL_DATABASE: "${MYSQL_DATABASE:-fivem}"
            MYSQL_USER: "${MYSQL_USER:-fivem}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "${DB_PORT:-3306}:3306"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - shiva
volumes:
    mysql-data:
networks:
    shiva:
        name: shiva
        driver: bridge
        external: true
